spring:
  application:
    name: authorization-server
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false


server:
  port: 1980
logging:
  level:
    org.springframework.security: debug
